name: eelwedding
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22833
title: "Bora & Dan's Wedding"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6d2dd'
    - '#6f0c4f'
    - '#ffffff'
    - '#a2628e'
    - '#822c66'
  brandStrength: 0.5
  lightness: 0.7673556297086179
  saturation: 1
  rhythmicContrast: 0.02098457282409072
purpose: []
