name: null
favicon: null
layout_spectrum: 0.2539729862473905
typography_spectrum: 0.09500167961232364
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6099142180755734
  lightness: 0.7673556297086179
  saturation: 0.8442902283277363
  rhythmicContrast: 0.02098457282409072
purpose: []
